# Generated by Django 2.1 on 2018-12-05 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='list',
            old_name='description',
            new_name='text',
        ),
    ]
